### ISSUE TITLE
Small Lua error

### ISSUE THREAD

**Issue by yoshimo** [destroyerdust/Class-Hall#10]
I get

> Message: ..\AddOns\ClassHall\ClassHall.lua line 139:
> bad argument #1 to 'ipairs' (table expected, got nil)
> Debug:
> [C]: ipairs()
> ClassHall\ClassHall.lua:139: OnEnter()
> Bazooka\Bazooka.lua:1576: showTip()
> Bazooka\Bazooka.lua:1381:
> Bazooka\Bazooka.lua:1372

This might be because Bazooka is trying to hide the bar itself, but i am not sure and having the icon and data about your garrison on your minimap is still desired.

This error happens on current live realms and outside the class order hall.

**Comment by destroyerdust** [comment]
Hi Yoshimo,

Thanks for the bug report, I'll go and replicate the bug tonight and resolve the issue.

Looks like on live realms the initialization of the follower database didn't get populated, could be a difference in wow API.

I do plan to phase out the minimap icon once I get the datatext part of the addon tested and working.

Thanks again for the bug report and feedback,
-DestroyerDust (Ahealen)

**Comment by destroyerdust** [comment]
@yoshimo I have pushed out V0.0.6. There was a small difference in how C_Garrison.GetFollowers function works from Beta to Live. There won't be any data in the list of information because this is designed for Class/Order Hall follower information vs the WoD Garrison information. But there shouldn't be any LUA Errors.
